---

#- hosts: nwn


- name: install compiler tools
  yum:
    name: "{{ compilertools }}"
    state: present

- name: install libs
  yum:
    name: "{{ libs }}"


- git:
   repo: 'https://github.com/NWNX/nwnx2-linux.git'
   dest: /usr/local/src/nwnx2
   clone: no
   update: no
  register: nwnx2_commit


- git: 
   repo: https://github.com/NWNX/nwnx2-linux.git
   dest: /usr/local/src/nwnx2
   clone: yes
  when: nwnx2_commit.before != nwnx2_commit.after 

- name: Creates build directory
  file:
    path: /usr/local/src/nwnx2/build
    state: directory


- name: check if nwnx2 is built (cmake)
  stat:
    path: /usr/local/src/nwnx2/build/cmake_install.cmake
  register: cmake_result

    
- name: build nwnx2 (cmake)
  shell:
    cmd: cmake ..
    chdir: /usr/local/src/nwnx2/build
    #when: cmake_result.stat.exists == False


- name: check if nwnx2 is built (make)
  stat:
    # path: /usr/local/src/nwnx2/build/compiled/"{{item}}"
    path: /usr/local/src/nwnx2/build/compiled/nwnx2.so
    #loop: "{{ nwnx2libs }}"
  register: nwnx2lib_stat

 

- name: build nwnx2 (make)
  make:
    chdir: /usr/local/src/nwnx2/build
  when: nwnx2lib_stat.exists == False


- name: copy *.so files to nwn
  copy:
    src: /usr/local/src/nwnx2/build/compiled/"{{item}}"
    dest: /home/neverwinter/nwn/"{{item}}"
    owner: neverwinter
    group: neverwinter
    mode: u+rw,g-rw,o-rwx
    remote_src: yes
  loop: "{{ nwnx2libs }}"


- name: copy nwn.service to nwn
  copy:
    src: nwn.service
    dest: /etc/systemd/system/nwn.service
    owner: root
    group: root



